# Generated by Django 5.1.1 on 2024-09-09 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="spending",
        ),
        migrations.AddField(
            model_name="spending",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="finances.category",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="category_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
