# Generated by Django 5.1.1 on 2024-09-18 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0002_remove_category_spending_spending_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Income",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateField()),
                ("description", models.TextField()),
            ],
        ),
    ]
